# nixpacks.toml - Angular frontend configuration

[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "npm install --production=false"
]

[phases.build]
cmds = [
  "ng build --configuration railway"
]

[start]
cmd = "npm run start:prod"
