# nixpacks.toml - .NET 9.0 configuration

[variables]
DOTNET_CLI_TELEMETRY_OPTOUT = "1"
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "1"
ASPNETCORE_URLS = "http://0.0.0.0:8080"

[phases.setup]
# Instalar .NET 9.0 específicamente
nixPkgs = [
  "dotnetCorePackages.dotnet_9.sdk",
  "icu",
  "zlib",
  "openssl"
]

# Forzar la instalación de .NET 9.0
cmds = [
  "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.0",
  "export PATH=$HOME/.dotnet:$PATH"
]

[phases.install]
cmds = [
  "dotnet restore backend/ECommerce.sln --nologo"
]

[phases.build]
# Publica específicamente el Product Service
cmds = [
  "dotnet publish backend/src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --no-restore -c Release -o out"
]

[start]
# Ejecuta el Product Service
cmd = "dotnet out/ECommerce.Product.API.dll"
