[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["dotnet restore backend/src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj"]

[phases.build]
cmds = ["dotnet publish backend/src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --no-restore -c Release -o out"]

[start]
cmd = "dotnet run --project backend/src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --configuration Release"
