# nixpacks.toml - .NET 9.0 compatible configuration

[variables]
# Fija la versión del SDK que instalará Nixpacks
NIXPACKS_CSHARP_SDK_VERSION = "9.0"
DOTNET_CLI_TELEMETRY_OPTOUT = "1"
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "1"

# Para ASP.NET Core: expone en 0.0.0.0:8080
ASPNETCORE_URLS = "http://0.0.0.0:8080"

[phases.setup]
# Usar dotnet-sdk genérico que incluye .NET 9.0
nixPkgs = [
  "dotnet-sdk",
  "icu",
  "zlib",
  "openssl"
]

[phases.install]
cmds = [
  "dotnet restore backend/ECommerce.sln --nologo"
]

[phases.build]
# Publica específicamente el Product Service
cmds = [
  "dotnet publish backend/src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --no-restore -c Release -o out"
]

[start]
# Ejecuta el Product Service
cmd = "dotnet out/ECommerce.Product.API.dll"
