[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["dotnet restore src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj"]

[phases.build]
cmds = ["dotnet publish src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --no-restore -c Release -o out"]

[start]
cmd = "dotnet run --project src/Services/Product/ECommerce.Product.API/ECommerce.Product.API.csproj --configuration Release"
