[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore ECommerce.Product.API.csproj"]

[phases.build]
cmds = ["dotnet build ECommerce.Product.API.csproj -c Release --no-restore"]

[start]
cmd = "dotnet run --project ECommerce.Product.API.csproj --configuration Release"
